[package]
name = "outbox"
version = "0.1.0"
edition = "2021"

[dependencies]
cdc-framework = { path = "../cdc-framework" }

postgres-protocol = { workspace = true }
tokio-postgres = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
