[package]
name = "application"
version = "0.1.0"
edition = "2021"

[dependencies]
outbox = { path = "../outbox" }

tokio = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
